import { SectionHeader } from "@/components/utils/SectionHeader";
import { Project } from "./Project";
import styles from "./projects.module.scss";
import tazzweed from "../../../public/project-imgs/Tazzweed.png";
import telefric from "../../../public/project-imgs/telefric.png";
import wilma from "../../../public/project-imgs/resturant.png";
import ecommerce from "../../../public/project-imgs/E-commerce.png";
import sortingAlgo from "../../../public/project-imgs/sortAlgo.png";

export const Projects = () => {
  return (
    <section className="section-wrapper" id="projects">
      <SectionHeader title="Projects" dir="r" />

      <div className={styles.projects}>
        {projects.map((project) => {
          return <Project key={project.title} {...project} />;
        })}
      </div>
    </section>
  );
};

const projects = [
  {
    title: "Tazzweed",
    imgSrc: tazzweed,
    code: "https://github.com/ammmarr/Tazzweed",
    projectLink: "https://tazzweed.com/",
    tech: ["React", "SASS Modules", "Typescript", "Framer-motion"],
    description:
      "I was a part of an amazing team of developers, to make sure that the website is looking amazing across all devices and browsers",
    modalContent: (
      <>
        <p>
          Tazzweed is an AI procurment service, offering various products and
          services generated by an AI Whastapp Bot.
        </p>

        <p>
          Its Backend System is built on a complete business software for
          analyzing their data
        </p>
        <p>
          I designed and imlpemented the design with multiple animations as
          needed
        </p>
        <p> </p>
        <p>
          - I was working with in this application by React, Typescript, and
          framer motion
        </p>

        <p>
          - I Implemented and read alot of libraries documantion to make sure
          that my website is working as expected
        </p>
      </>
    ),
  },
  {
    title: "Telefric",
    imgSrc: telefric,
    code: "https://github.com/ammmarr",
    projectLink: "https://app.telefreik.com",
    tech: ["React", "TailWind CSS", "Typescript"],
    description:
      "Worked with a team of developers, designers,and testers in developing this application.I enjoyed working in more of a encouraging team enviroment.",
    modalContent: (
      <>
        <p>
          Telefric is a startup in Egypt looking making transportation methods
          much more convinient
        </p>
        <p>
          With already more than 50000 Users, it is showing alot of signs about
          its future
        </p>

        <p>
          There were alot of work to be done and code to be refactored. It was a
          bit of a challenge but I learned alot in developing it with my Team
        </p>
        <p>
          I made sure that figma desings are translated into pixel perfect
          quality ={">"}
        </p>
        <p> </p>
        <p>- I was working with in this application by React, Typescript</p>

        <p>
          - I Implemented and read alot of libraries documantion to make sure
          that my website is working as expected
        </p>
      </>
    ),
  },
  {
    title: "Wilma",
    imgSrc: wilma,
    code: "https://github.com/ammmarr/FreelancingResturantApp",
    projectLink: "https://freelancing-1.vercel.app/",
    tech: ["NextJS", "MongoDb", "Typescript", "SASS Modules", "Framer-motion"],
    description:
      "First freelancing project for an italian Resturant owner. A Resturant app for resturant owners. This app is my baby, designed and built on my own.",
    modalContent: (
      <>
        <p>
          Wilma is a real-time Resturant Application for resturant owners. This
          app is my baby, designed and built on my own.
        </p>
        <p>
          The tech stack is based on top of NextJS for the mobile app, connected
          to a Nextjs api Routes, with data stored in MongoDB, demo deployed on
          Vercel.
        </p>

        <p>
          What i really struggled with at first was connecting the database,
          Turns out Nextjs Had alot of problems saving and Running Mongoose,
          Needles to say everything is solved now :)
        </p>
        <p>here are more info why I chosen what I have chosen ={">"}</p>
        <p> </p>
        <p>
          - I have chosen to build this application using the latest NextJS for
          its unique features as SSR, SEO optimization, and Images handling and
          responisvness
        </p>
        <p>- used framer motion to add some cool interactive animations</p>

        <p>- used JWT for protecting routes and admin login </p>
        <p>- used MonogDB AS the Main DataBase</p>
        <p>- used SASS Modules for styling and responsiveness</p>
        <p>- used Formik and Yup for form validation and handling</p>
        <p>
          - I surely practiced the SOLID princibles for writing clean and
          maintainable code
        </p>
      </>
    ),
  },

  {
    title: "Ecommerce Furniture Store",
    imgSrc: ecommerce,
    code: "https://github.com/ammmarr/movies-surfer",
    projectLink: "https://ammmarr.github.io/movies-surfer/",
    tech: ["React", "Redux", "Javascript", "Firebase"],
    description: "A Fully Functional E-commerce Web application with ).",
    modalContent: (
      <>
        <p></p>
        <p>
          The Online Furniture Store is a modern e-commerce platform that offers
          a wide range of furniture products for customers looking to enhance
          their home or office spaces. This platform was developed using
          cutting-edge technologies, including React, Redux, JavaScript, and
          Firebase, to provide users with a seamless shopping experience.
        </p>
        <p>Key Features:</p>
        <p>
          User Authentication: Users can create accounts, log in, and securely
          manage their profiles, including cart details, thanks to Firebase
          Authentication.
        </p>
        <p>
          Product Listings: The platform offers a vast catalog of furniture
          items, categorized for easy navigation. Users can filter products
          based on various criteria, such as price. Shopping Cart: With Redux
          managing the application state,
        </p>
        <p>
          {" "}
          users can easily add and remove items from their shopping cart. Cart
          contents are persisted across sessions, ensuring a seamless shopping
          experience.
        </p>
        <p>
          {" "}
          Search Functionality: Users can quickly find specific products using a
          robust search feature, enhancing the overall user experience.
        </p>
        <p>
          Responsive Design: The platform is designed to be responsive, ensuring
          a consistent and user-friendly experience across various devices,
          including desktops, tablets, and smartphones.
        </p>
        <p>
          Real-time Updates: Firebase &apos;s real-time database capabilities
          enable instant updates to product availability and stock information.
          Conclusion:
        </p>
      </>
    ),
  },

  {
    title: "Sorting algorithms visualizer",
    imgSrc: sortingAlgo,
    code: "https://github.com/ammmarr/sorting-algorithms-visualizer",
    projectLink: "https://ammmarr.github.io/sorting-algorithms-visualizer/",
    tech: ["React", "Typescript", "Redux", "SCSS"],
    description:
      "From its name, Its a the main sorting algorithsm visualization application",
    modalContent: (
      <>
        <p>
          This application is basically a way of visualizing the main Sorting
          algorithms,
        </p>
        <p>
          I consider this one of the most challenging projects I have ever
          worked on,
        </p>
        <p>
          I really enjoyed building it despite all the challenges I had to face
          during the process of developing it, from animating and implementing
          the algorithms to designing and visualizing them,
        </p>
        <p>
          I have utilized the latest React18 technologies with Redux for
          managing the state
        </p>
      </>
    ),
  },
];
